# Generated by Django 4.2.3 on 2023-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='static/menu_images/Untiteld.jpg', upload_to='static/menu_images/'),
        ),
    ]
