# Generated by Django 4.2.3 on 2023-08-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
