# Generated by Django 4.2.3 on 2023-08-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0009_remove_userinfo_password_userinfo_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password1',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password2',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
