# Generated by Django 4.2.3 on 2023-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0010_alter_userinfo_password1_alter_userinfo_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
