# Generated by Django 4.2.3 on 2023-08-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0011_alter_userinfo_password1_alter_userinfo_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
