# Generated by Django 4.2.3 on 2023-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0012_rename_phone_userinfo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
