# Generated by Django 4.2.3 on 2023-08-20 17:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0016_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
