# Generated by Django 4.2.3 on 2023-08-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0020_userprofile_password_alter_userprofile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
