# Generated by Django 4.2.3 on 2023-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0021_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='total_recipe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
