# Generated by Django 4.2.3 on 2023-08-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0024_rename_recipe_menuitem_total_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='total_recipe',
        ),
    ]
