# Generated by Django 4.2.3 on 2023-08-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0026_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
