# Generated by Django 4.2.3 on 2023-08-29 11:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0030_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'SuperUser'), ('staff', 'StaffUser'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
