# Generated by Django 4.2.3 on 2023-08-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggaapp', '0031_alter_userprofile_managers_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
